#! /bin/bash
sudo yum -y install httpd
sudo sh -c "echo '<html><h1>The AMI generated by Packer Version is 1.0</h1></html>' > /var/www/html/index.html"
sudo systemctl enable httpd.service
sudo systemctl start httpd.service