#! /bin/bash
sudo yum -y install ruby
cd /home/ec2-user
wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
chmod +x ./install
sudo ./install auto
sudo systemctl start codedeploy-agent
sudo systemctl enable codedeploy-agent
sudo systemctl is-active codedeploy-agent

sudo yum -y install httpd
sudo sh -c "echo '<html><h1>The AMI generated by Packer Version is 1.0</h1><body>TEMP</body></html>' > /var/www/html/index.html"
sudo systemctl enable httpd.service
sudo systemctl start httpd.service